### PR TITLE
Warning for invalid Tested up to value

### LINKED ISSUE #609: Warn if Tested up to value in readme exceeds the released version of WP
Lets say, current stable version is `6.6`. If the value is `6.8` or above, there should be a warning.

```
ERROR: Tested up to: 6.8 - This version of WordPress does not exist (yet).
```

### PR DESCRIPTION
**Pull request by ernilambar**
Fixes https://github.com/WordPress/plugin-check/issues/609

### CODE REVIEW

**Review by davidperezgar — APPROVED** [review]

**Comment by swissspidy** [comment]
Could we add tests for this? :-)

* Latest WP version
* Latest +1
* Latest +2

**Comment by ernilambar** [comment]
@swissspidy I was thinking about using similar test like `test_run_with_errors_parser_warnings_with_custom_set_transient_version()`. Should we add three separate test plugins for this? Or is there any better approach?

**Comment by swissspidy** [comment]
Mocking the transient makes sense to me. We have way too many test plugins already 😄

**Comment by ernilambar** [comment]
Unit test added.

**Review by swissspidy — APPROVED** [review]

**Pull request merged**
