### PR TITLE
Add support for severity levels for warnings and errors

### LINKED ISSUE #479: Create a better solution for severity levels
Another thing we'd have to change before we can integrate on w.org is a more flexible "severity levels" solutions. Currently, we have 2 array variables `$errors` and `$warnings` but we need to be able to extend this.

For the w.org integration specifically we need a higher level than error, called (something along the lines of) "blocking". If this is > 0, the submission will not be allowed to .org. This is mainly because we can't automatically block every error, because of false positives. And reducing errors to warning because of this reason feels wrong.

Also, in the future, I'd love to see something like a "notice" added with suggestions / best practices.
I suggest we move away from having a variable per "level" and move into a more extendable way of setting this up via a "severity level collection" like solution. This way other people can even add (or remove) levels via a filter for example.

Relevant file: https://github.com/WordPress/plugin-check/blob/trunk/includes/Checker/Check_Result.php#L31

I'll also add this in the doc / plan. Love to hear your thoughts on this.

---

Talked this over with @joemcgill in Slack, we discussed the possibility for having different ruleset xml files and/or using PHPCS severity levels. This solves the PHPCS side of things, but PCP has more (and will have a lot more in the future) checks not related to PHPCS. We need to support multiple severity levels for this as well.

### PR DESCRIPTION
**Pull request by ernilambar**
Fixes https://github.com/WordPress/plugin-check/issues/479

* Default severity level for check is `5`
* `--severity` argument is added for `wp plugin check`

Example:

```
# Show errors and warnings with severity greater or equal to 7
wp plugin check foo-sample --severity=7   
```

### CODE REVIEW

**Comment by ernilambar** [comment]
Since we don't have different severity level in our checks currently I have not added any tests. After this PR is merged https://github.com/WordPress/plugin-check/pull/518 (some strange issue has appeared), we can add tests with multiple severity levels.

**Comment by ernilambar** [comment]
PR has been updated with feature tests.

**Comment by davidperezgar** [comment]
For me it seems correct. Where do we put the severity in check? I'd update some documentation in the plugin about severity levels.

**Comment by ernilambar** [comment]
For sniffer rules, we can assign severity like this in `phpcs-rulesets/plugin-review.xml`:

```
<rule ref="WordPress.WP.PostsPerPage">
  <severity>9</severity>
</rule>
```

For other type of check like `add_result_error_for_file()` or `add_result_warning_for_file()`, there is addition of new parameter for `severity`

```
$this->add_result_error_for_file(
  $result,
  __( 'Prohibited text found.', 'pcp-addon' ),
  'prohibited_text_detected',
  $file,
  0,
  0,
  8
);
```
In this example, `8` is set as severity for the `prohibited_text_detected` check.

For checks which are extended from `Abstract_PHP_CodeSniffer_Check`, like following, I could not find the way to change the severity level:

```
protected function get_args() {
	return array(
		'extensions' => 'php',
		'standard'   => 'WordPress',
		'sniffs'     => 'WordPress.WP.I18n',
	);
}
```

**Comment by ernilambar** [comment]
Currently several readme warnings are kept under same error code `readme_parser_warnings`. If we need to have separate severity level for separate error code then we need to keep unique error code for each warnings. 
Ref: https://github.com/WordPress/plugin-check/blob/trunk/includes/Checker/Checks/Plugin_Repo/Plugin_Readme_Check.php#L538

**Comment by davidperezgar** [comment]
I think they are all Warnings.

**Comment by davidperezgar** [comment]
Thanks Nilambar, you have solved the conflicts and we have now new argument for severity.

**Review by davidperezgar — APPROVED** [review]

**Comment by swissspidy** [comment]
What about the suggestion at https://github.com/WordPress/plugin-check/issues/479#issuecomment-2244894651 to have separate severity levels for warnings and errors

**Comment by ernilambar** [comment]
PR updated with feature tests and also with separate severity arguments.

**Comment by davidperezgar** [comment]
Why did you separate the severity?

I undestood that 0-5 is warning, and 6-10 is error. After that, we have different severity levels. I think is less complicated.

**Comment by swissspidy** [comment]
This was suggested at https://github.com/WordPress/plugin-check/issues/479#issuecomment-2244894651

let‘s discuss it there

seperate levels brings more flexibility

**Comment by ernilambar** [comment]
> Why did you separate the severity?
> 
> I undestood that 0-5 is warning, and 6-10 is error. After that, we have different severity levels. I think is less complicated.

This is not the approach this PR has implemented. Since our significant checks used PHPCS, it'd better we follow the similar approach it follows.

**Comment by davidperezgar** [comment]
Ok

**Review by swissspidy — APPROVED** [review]
Looks good to me but would appreciate more reviews.

**Comment by davidperezgar** [comment]
Ok, I ping to others.

**Comment by barrykooij** [comment]
Look great. I agree keeping separate levels for warnings and errors for that extra bit of flexibility. For plugin repo specific checks, we'll have an extra look afterward if all levels are the way we like, but that's non-blocking for this PR.

**Review by barrykooij — APPROVED** [review]

**Comment by davidperezgar** [comment]
Perfect!

**Pull request merged**
