### PR TITLE
Add new plugin banner and icon

### LINKED ISSUE #631: New image for the Plugin Check Plugin
I suggest to make a new design for the Plugin in wordpress.org. In the PR we can see different options.

### PR DESCRIPTION
**Pull request by davidperezgar**
Fixes #631 
Images designed by [Álvaro Dallas](https://profiles.wordpress.org/alvarodallas/)

### CODE REVIEW

**Review by swissspidy — APPROVED** [review]

**Review by ernilambar — APPROVED** [review]

**Review by felixarntz — COMMENTED** [review]
@davidperezgar The text "Ease the Review Process WordPress.org" reads weird to me. Better would be something like:
* "Ease the WordPress.org Review Process"
* "Ease the Plugin Review Process"
* "Ease the Review Process"

**Comment by davidperezgar** [comment]
Ok! I'll update it! Thanks!

**Comment by davidperezgar** [comment]
Done!

**Comment by felixarntz** [comment]
Thanks @davidperezgar!

**Comment by davidperezgar** [comment]
Thanks to you!!! ;)

**Pull request merged**
