### PR TITLE
Update build dev dependency

### PR DESCRIPTION
**Pull request by mukeshpanchal27**
In PR #166, we established separate development dependencies for `lint`, `phpmd`, and `phpstan`. Therefore, we should ensure that these dependencies are updated alongside the main composer dependencies. This PR updates the WPCS dependency to the latest version.

### CODE REVIEW

**Review by swissspidy — APPROVED** [review]
We should really just enable Dependabot in this repo

**Comment by joemcgill** [comment]
@swissspidy it looks like we already have Dependabot running here, see [this list of PRs](https://github.com/WordPress/plugin-check/pulls?q=is%3Apr+author%3Aapp%2Fdependabot+). Do you have something more specific in mind?

[UPDATE] Looks like we only have it set up for security updates, not regular dependency updates. We have #108 already in the backlog for this.

**Review by joemcgill — APPROVED** [review]
These changes look good to me in the meantime.

**Comment by mukeshpanchal27** [comment]
Thank you, @joemcgill and @swissspidy. Let's continue the discussion on the tracking issue. I will proceed to merge this PR.

**Pull request merged**
