### PR TITLE
Exclude test-content from the built zip.

### PR DESCRIPTION
**Pull request by dd32**

### CODE REVIEW

**Comment by ernilambar** [comment]
This folder is needed to run Runtime Checks.

**Comment by ernilambar** [comment]
Related https://github.com/WordPress/plugin-check/pull/427

**Comment by dd32** [comment]
Huh, very weirdly named for that purpose :)

**Comment by swissspidy** [comment]
Yes we should really rename it

**Comment by ernilambar** [comment]
👍 on renaming. `runtime-content` or something?

**Comment by swissspidy** [comment]
Yeah that works

**Comment by davidperezgar** [comment]
I thought the same, that it was a weird name. +1 to runtime-content.

**Pull request closed without merging**
