### PR TITLE
Add missing messages for missing readme parser warnings

### LINKED ISSUE #588: Missing warning messages for trimmed readme section
**Missing warning messages for trimmed readme section**

Eg:

`readme_parser_warnings_trimmed_section_description`, `readme_parser_warnings_trimmed_section_faq`, etc

Screenshot:

Screenshot 2024-08-28 at 1 18 13 PM

### PR DESCRIPTION
**Pull request by ernilambar**
Fixes https://github.com/WordPress/plugin-check/issues/588

### CODE REVIEW

**Comment by ernilambar** [comment]
Screenshot
Screenshot 2024-08-28 at 3 13 28 PM

**Comment by ernilambar** [comment]
Could this be shipped in `1.1`?

**Review by swissspidy — APPROVED** [review]

**Comment by swissspidy** [comment]
> Could this be shipped in `1.1`?

I'll defer to @davidperezgar. If he approves the PR, we can merge it before the release

**Review by davidperezgar — APPROVED** [review]

**Comment by davidperezgar** [comment]
Yes! it's ok!

**Pull request merged**
