### PR TITLE
Add Spell Check action

### PR DESCRIPTION
**Pull request by mukeshpanchal27**
Follow-up of #245 

Added new CI for Spell Check that show error at the moment.

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by joemcgill** [comment]
Thanks @mukeshpanchal27. The output looks good, but it would be nice if these were all reported as warnings instead of causing the check to fail. Can you see if that's possible?

**Comment by mukeshpanchal27** [comment]
Hello @joemcgill, it appears that the action didn't offer any configuration to generate warnings instead of errors. I've raised the issue and created a ticket here: https://github.com/crate-ci/typos/issues/811 on the main repository. We will keep you posted once there are any updates on this matter.

**Comment by swissspidy** [comment]
I think treating as errors is fine, but we should first merge that other PRs

**Comment by joemcgill** [comment]
Thanks for checking, @mukeshpanchal27. Let's go ahead do what Pascal suggests, and merge the PR that fixes the current errors, and then merge trunk back into this PR to make sure we have things passing before merging this, so we don't introduce a blocker to other PRs.

**Comment by mukeshpanchal27** [comment]
@joemcgill @felixarntz @swissspidy The PR is ready for review.

**Review by swissspidy — APPROVED** [review]

**Review by felixarntz — APPROVED** [review]
Thanks @mukeshpanchal27!

**Pull request merged**
