### PR TITLE
When checking for excluded files, use the normalized path to ensure that it works in Windows environments.

### LINKED ISSUE #693: CLI: ensure `--exclude-files` works in Windows
#592 fixed things so that `--exclude-directories` works in Windows environments.

This is a follow-up to #592 to ensure `--exclude-files`  works in Windows environments.

PR coming shortly.

### PR DESCRIPTION
**Pull request by pbiron**
Fixes #693

### CODE REVIEW

**Comment by pbiron** [comment]
@davidperezgar can you please look at this PR before v1.2.0 ships?

**Comment by davidperezgar** [comment]
I don't know for sure, we're in final stages of version.

**Comment by pbiron** [comment]
the reason I would really like to get it into 1.2.0 is that it is a follow-up to #592 which will be included in 1.2.0.  #592 fixed one prob for the WP_CLI command in Windows but missed another one.

**Comment by ernilambar** [comment]
I don't have Windows setup to test the PR. Can someone please verify who is in Windows OS?

**Review by swissspidy — APPROVED** [review]

**Comment by swissspidy** [comment]
I trust that @pbiron did the necessary testing when fixing this bug on their machine :)

**Review by ernilambar — APPROVED** [review]

**Pull request merged**
