### PR TITLE
Add admin notice for live preview blueprint

### PR DESCRIPTION
**Pull request by huzaifaalmesbah**
This pull request introduces an admin notice to the live preview blueprint, designed to remind users that they are viewing a preview and to highlight the Playground feature.

Huzaifa-20240902094322

### Testing Instructions:
To test this feature:
1. Navigate to the [Blueprint Builder](https://playground.wordpress.net/builder/builder.html) tool.
2. Replace the default JSON with the `blueprint.json` file from this plugin.
3. Click `Run It` to see the preview in action.

### CODE REVIEW

**Comment by rejaulalomkhan** [comment]
It's working and very helpful for developers. Thanks for the excellent PR @huzaifaalmesbah

**Comment by mukeshpanchal27** [comment]
Why do you think it's necessary to include this additional notice? If it were necessary, the playground would have already done that. Also, I don't think PCP uses the `Live Preview` feature.

**Comment by huzaifaalmesbah** [comment]
> Why do you think it's necessary to include this additional notice? If it were necessary, the playground would have already done that. Also, I don't think PCP uses the `Live Preview` feature.

Thanks for the feedback, @mukeshpanchal27. The notice is meant to improve clarity for users in preview mode, especially those new to the Playground feature. Even if PCP doesn't use Live Preview, this helps maintain consistency. If you think it's not needed, we can avoid it.

**Comment by swissspidy** [comment]
I agree with Mukesh here, we don‘t even use Live Preview.

If you think people using Live Preview need a little reminder thaf they are using Playground (why would they though?), I recommend opening a feature request on Playground itself. Adding such a notice to every single plugin is not scalable.

**Comment by davidperezgar** [comment]
Yes, It's much better to propose it in Playground.

**Pull request closed without merging**
