### PR TITLE
Update WPCS to `dev-develop` branch at a specific commit

### LINKED ISSUE #136: Exception thrown by I18nSniff in PHP 8.1
While testing in PHP 8.1 all warnings from the `I18n_Usage_Check` are replaced by the following Exception thrown. It looks as though the issue is to do with WPCS dependency rather than the plugin check itself but we may want to consider how this is handled? 

image

```
An error occurred during processing; checking has been aborted. The error message was: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/html/wp-content/plugins/plugin-check/vendor/wp-coding-standards/wpcs/WordPress/Sniffs/WP/I18nSniff.php on line 194
```

### PR DESCRIPTION
**Pull request by mukeshpanchal27**
Closes #136 

### How to test the Change

1. Take the pull from the branch.
2. Set `phpVersion: 8.1` in your `.wp-env.json` file and restart environment.
4. Update composer. Use `composer update` command.
5. Go to Admin Panel > Tools > Plugin Check > Check plugin

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by mukeshpanchal27** [comment]
PHPCS shows `- The package "wp-coding-standards/wpcs" is pointing to a commit-ref, this is bad practice and can cause unforeseen issues.` error because we use unstable version.

**Comment by swissspidy** [comment]
The warning is coming from `composer validate --strict` specifically, not PHPCS. It's usually just a warning, but `--strict` makes it error.

The only way to resolve this is by not using `--strict` for the time being.

Aside, [a note from the Composer docs](https://getcomposer.org/doc/04-schema.md#package-links) about using explicit commit references:

> This feature has severe technical limitations, as the `composer.json` metadata will still be read from the branch name you specify before the hash. You should therefore only use this as a temporary solution during development to remediate transient issues, until you can switch to tagged releases. The Composer team does not actively support this feature and will not accept bug reports related to it.

It's definitely a temporary solution in this case, so IMHO it should be fine to temporarily remove `--strict` as well.

**Comment by spacedmonkey** [comment]
@mukeshpanchal27 The composer install is now failing in CI.

**Comment by mukeshpanchal27** [comment]
@swissspidy, the CI still shows that warning and throws the error.

**Comment by swissspidy** [comment]
The warning is expected to be there still. The step still fails now because of the additional `The lock file is not up to date with the latest changes in composer.json` error. That is new.

**Comment by mukeshpanchal27** [comment]
Thanks, @spacedmonkey, for helping me correct the composer version issue.

**Review by spacedmonkey — APPROVED** [review]

**Review by swissspidy — APPROVED** [review]

**Review by felixarntz — APPROVED** [review]

**Pull request merged**
