### PR TITLE
Include assets for WP.org

### PR DESCRIPTION
**Pull request by bordoni**
### Description of the Change

Uploaded to the Repo already.

image

I took some of the existing [Dashicons](https://icon-sets.iconify.design/dashicons/) modified a bit and made the assets,
I've used the WordPress blue and Grey for the header and just the blue for the Icon.

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Review by felixarntz — COMMENTED** [review]
Thanks @bordoni!

Quick question, why are those added to `.assets`? Based on https://github.com/10up/action-wordpress-plugin-deploy#optional-environment-variables, shouldn't they be in a `.wordpress-org` directory?

Separate question: I assume we should also add those assets to the `trunk` branch?

**Comment by bordoni** [comment]
Oh yeah I will do the move! Thanks for the review

**Comment by bordoni** [comment]
Done.

**Review by felixarntz — APPROVED** [review]
LGTM!

One follow up question: Are the `icon-128x128.png` and `icon-256x256.png` files intentionally missing? Not sure if the `icon.svg` works everywhere, so we may want to add those two versions as well. Not a blocker though.

**Comment by bordoni** [comment]
I didn't know about the `.svg` not working in some places.
I will add the others in a separate PR.

**Pull request merged**
