### PR TITLE
Fix typos in the plugin

### LINKED ISSUE #245: Fix typos in the plugin
### Is your enhancement related to a problem? Please describe.

There are misspellings someplace in the plugin; check https://github.com/mukeshpanchal27/typos-on-you/actions/runs/5817199880/job/15771497733.

### Designs

_No response_

### Describe alternatives you've considered

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by mukeshpanchal27**
Closes #245

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by mukeshpanchal27** [comment]
PHPCS shows - `The package "wp-coding-standards/wpcs" is pointing to a commit-ref, this is bad practice and can cause unforeseen issues. error because we use unstable version.`

@swissspidy I follow same steps that we did for https://github.com/10up/plugin-check/pull/163#issuecomment-1545316907 but still it not working in local could you guide me why it not working when i run `composer update` or `composer install`

**Comment by swissspidy** [comment]
@mukeshpanchal27 That's just a warning, not an error. The actual error is that the lock file is now out of date because of the fixed typo in `composer.json`

```
# Lock file errors
- The lock file is not up to date with the latest changes in composer.json, it is recommended that you run `composer update` or `composer update <package name>`.
# General warnings
- The package "wp-coding-standards/wpcs" is pointing to a commit-ref, this is bad practice and can cause unforeseen issues.
- require.automattic/vipwpcs : exact version constraints (2.3.3) should be avoided if the package follows semantic versioning
```

Just running `composer update` fixes this.

**Comment by mukeshpanchal27** [comment]
Thanks @swissspidy for the quick reply.

If we check same for trunk then also we get same error 🤔, I have tried `composer update` and `composer install` but it show same error for me.

Screenshot 2023-08-16 at 2 12 56 PM

**Comment by swissspidy** [comment]
Still just warnings, not errors. They can be safely ignored.

**Comment by swissspidy** [comment]
Let‘s merge trunk, resolve conflicts and run composer update. Then this one is good to go

**Comment by mukeshpanchal27** [comment]
Thanks @swissspidy, The PR is ready for review. cc. @joemcgill @felixarntz

**Review by swissspidy — APPROVED** [review]

**Review by felixarntz — APPROVED** [review]
Thanks @mukeshpanchal27!

**Pull request merged**
