### PR TITLE
Allow runtime initialization even when only addon checks are requested

### PR DESCRIPTION
**Pull request by felixarntz**
This should fix the 3rd problem outlined in https://github.com/WordPress/plugin-check/issues/597#issuecomment-2327483452. Also see [explanation of the approach](https://github.com/WordPress/plugin-check/issues/597#issuecomment-2332289958).

Note that this will only make sense to be tested in combination with #608.

### CODE REVIEW

**Comment by felixarntz** [comment]
@swissspidy Once #608 is merged, let's give this one a try. At the very least, it should fix part of the remaining problem with addon runtime checks.

**Comment by swissspidy** [comment]
> Could you give it a try to implement a Behat test that runs two runtime checks, one from the addon and one built-in one?

Doesn't work. When I use e.g. ` --checks=non_blocking_scripts,example_runtime` I still get `Error: Check with the slug "example_runtime" does not exist.`.

**Review by swissspidy — APPROVED** [review]

**Comment by felixarntz** [comment]
@swissspidy You approved this, but I wonder whether we should keep it open until we figured out what else is missing. Just want to make sure we're not introducing something here that's wrong. WDYT?

Maybe we should reactivate those failing Behat tests in this PR and work towards making them pass.

**Comment by swissspidy** [comment]
Whether we do smaller PRs or try to fix everything in this PR, either works for me

**Comment by felixarntz** [comment]
That's fair. I guess this fixes at least part of the problem, so we could already merge it.

**Review by ernilambar — APPROVED** [review]

**Pull request merged**
